### PR TITLE
Avoid generating invalid USE flag combinations

### LINKED ISSUE #52: use correct use flags for testing
Currently testing is just done using "FEATURES=test emerge …", which often enough fails because of missing use flags. This should be detectable using the portage API when writing the scripts so the test has a chance of actually succeeding.

### PR DESCRIPTION
**Pull request by hsoft**
Consider ignored (through `ignoreprefix`) USE flags that are enabled on
the system as "always on" in `REQUIRED_USE` checks of possible
combinations. This makes us avoid generating invalid combinations.

For example, on a system with `FEATURES=test`, a package with `test? (
foo bar )` will always generate a USE line with `foo bar` in it.

Also, fix the call to portage's `check_required_use()`: it expects a
list, not a string.

fixes #52

### CODE REVIEW

**Comment by hsoft** [comment]
@DerDakon you mentioned earlier that you didn't know much about Python, but you're pretty much the only recent contributor to the project. Who do you think could be in good position, in terms of Python skills and project knowledge, to review this PR?

**Comment by DerDakon** [comment]
I have this patched on my local build machines and will test if it works, that will hopefully be enough.

**Comment by DerDakon** [comment]
This does not set the correct useflags for rdeps, no? You could look on the rdeps of bug 659234 for hppa for the moment.

**Comment by hsoft** [comment]
To be sure: are you expecting this PR to solve all outstanding issues?

**Comment by hsoft** [comment]
I see what you mean: tatt injects `test` through `--test`. If the `test` USE flag isn't enabled when tatt is ran (when the script is generated), the USE flag combinations aren't going to restrict themselves (because portage, at the time tatt runs, doesn't have `test` enabled for the target package).

This is a further bug that can be fixed, yes. However, you can verify that this PR fixes *something* by enabling `test` for kvazaar on your machine when you run `tatt` on the very same bug. If you run it on the `master` branch, you'll see that you get a `-static-libs` run. If you run it on my PR branch, you'll see that it the `-static-libs` run is ignored.

**Comment by DerDakon** [comment]
I can't see a difference between the unpatched and the patched version. Am I missing something essential?

**Comment by hsoft** [comment]
The difference is that, if you enable `FEATURE=test`, this PR is going to properly eliminate the `-static-libs` from bug 671044's run, something that the master branch doesn't do (even if it has `FEATURE=test`)

**Comment by DerDakon** [comment]
No, it doesn't, in fact both have no use flags set. Read again or look into the ebuild:

```bash
REQUIRED_USE="test? ( static-libs )"
```

It should _add_ static-libs.

**Comment by hsoft** [comment]
I know.

My wild guess is that you're not running the version of tatt you think you're running. You could verify by inserting an `assert 0` somewhere important: if tatt continues to work, then you're not running the right code. Here's my full output so we can compare:

```
$ cat /etc/portage/package.env
media-libs/kvazaar test
$ ./env/bin/tatt -b 671044
Bugnumber:  671044
Stabilization bug detected.
Jobname: kvazaar-671044
Found the following package atom : =media-libs/kvazaar-1.2.0-r1
Unmasked =media-libs/kvazaar-1.2.0-r1 in /etc/portage/package.keywords/archtest
  =media-libs/kvazaar-1.2.0-r1: ignoring invalid USE flag combination {'test'}
Success Report script written to kvazaar-671044-success.sh
Commit script written to kvazaar-671044-commit.sh
$ cat kvazaar-671044-useflags.sh
#!/bin/bash
#USE-Flag build tests for job kvazaar-671044

trap "echo 'signal captured, exiting the entire script...'; exit" SIGHUP SIGINT SIGTERM

export TATT_TEST_TYPE="use"
export TATT_REPORTFILE="kvazaar-671044.report"
export TATT_BUILDLOGDIR=""
export TATT_EMERGEOPTS=""

source "/home/vdupras/src/tatt/templates/tatt_functions.sh"

echo -e "USE tests started on $(date)\n" >> kvazaar-671044.report

# Code for =media-libs/kvazaar-1.2.0-r1
 tatt_test_pkg --test "=media-libs/kvazaar-1.2.0-r1"
USE='static-libs' tatt_test_pkg "=media-libs/kvazaar-1.2.0-r1"

echo >> kvazaar-671044.report
```

Notice the `=media-libs/kvazaar-1.2.0-r1: ignoring invalid USE flag combination {'test'}` which is the important part that you should get as well.

**Comment by DerDakon** [comment]
Even then it's wrong: tatt_test_pkg does a build test. It runs FEATURES=test if you pass the option "--test". The result we need and that I have never seen until now would look like this:

```bash
USE='static-libs' tatt_test_pkg --test "=media-libs/kvazaar-1.2.0-r1"
USE='static-libs' tatt_test_pkg "=media-libs/kvazaar-1.2.0-r1"
USE='-static-libs' tatt_test_pkg "=media-libs/kvazaar-1.2.0-r1"
```

**Comment by hsoft** [comment]
Oh, never mind, I give up.

**Pull request closed without merging**
